Implemetation of the API call
ezequielsetzesglobant/RxAndroid pull request #2
Opened 2021-08-09 19:39 UTC by ezequielsetzesglobant

The API call was implemented to display the results in a CardView in a RecyclerView

Pixel
https://user-images.githubusercontent.com/84338513/128764218-eab70618-596f-4118-a2b0-c87fc046e7a5.mp4

Nexus
https://user-images.githubusercontent.com/84338513/128764156-3a5e3454-1ad5-4d20-95bb-87d35dd5a36a.mp4

2021-08-09 20:08 UTC, BQuinteros commented on app/src/main/java/com/example/rxandroid/data/api/WeatherAPI.kt
> +    @GET("onecall?")
I think this is not the correct API we call

2021-08-10 18:05 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/rxandroid/data/api/WeatherAPI.kt
> +    @GET("onecall?")
done

2021-08-10 18:50 UTC, SartiMau requested changes

2021-08-10 18:50 UTC, SartiMau commented on app/src/main/java/com/example/rxandroid/data/mapper/WeatherMapper.kt
> +fun ForecastApiResponse.transform() = ForecastApiEntity(
all these functions should be public?

2021-08-10 18:50 UTC, SartiMau commented on app/src/main/java/com/example/rxandroid/data/mapper/WeatherMapper.kt
> +
delete this extra line pls

2021-08-10 18:50 UTC, SartiMau commented on app/src/main/java/com/example/rxandroid/data/service/WeatherService.kt
> +        private const val APP_KEY: String = "46a38f32b732c581ed6e50a148147864"
put this key in a gradle variable pls

2021-08-10 19:18 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/rxandroid/data/mapper/WeatherMapper.kt
> +
done

2021-08-10 19:18 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/rxandroid/data/mapper/WeatherMapper.kt
> +fun ForecastApiResponse.transform() = ForecastApiEntity(
changed

2021-08-11 14:14 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/rxandroid/data/service/WeatherService.kt
> +        private const val APP_KEY: String = "46a38f32b732c581ed6e50a148147864"
done

2021-08-11 14:19 UTC, BQuinteros approved these changes

2021-08-11 14:29 UTC, SartiMau approved these changes

2021-08-11 15:10 UTC, mauroLonghi approved these changes

2021-08-11 15:23 UTC, merged